freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-1
  env:
    CIRRUS_WORKING_DIR: /tmp/go/src/github.com/billziss-gh/cgofuse
    GOPATH: /tmp/go
  install_script:
  - kldload fuse
  - pkg install -y go fusefs-libs
  build_script:
  - go build -v ./fuse
  - go build -v ./examples/memfs
  - go test -v ./fuse
